name: main

on: push

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1

      - run: bun i

      - run: bun run build:model

      - run: bun run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/master'
        uses: actions/deploy-pages@v4

      - name: Deploy static asset to vercel
        if: github.ref == 'refs/heads/master'
        run: |
          mkdir -p .vercel/output
          echo '{"version":3}' > .vercel/output/config.json
          cp -r dist .vercel/output/static

          bunx vercel --prod --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
